export const COOKIE_TOKEN = "access_token"
export const COOKIE_USER_NAME = "user_name"
export const COOKIE_USER_PERMISSION = "user_role"
export const TYPE_KEEPING_TIME = "timekeeping"
export const TYPE_SALARY = "salary"
export const ROLE_HRM_ADMIN = "HRM_ADMIN"
