version: '3'
services:
  nodejs:
    image: $IMAGE:DEPLOY_TAG
    container_name: hrm-webapp
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
