version: '3'
services:
  nodejs:
    image: hub.saigonbpo.vn/img_sgb/nginx-hrm-webapp:dev
    container_name: hrm-webapp
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
