export const SAVE_SETTING = "SAVE_SETTING"
export const SHOW_ERROR = "SHOW_ERROR_SETTING_PAGE"
export const SHOW_LOADING = "SHOW_LOADING_SETTING_PAGE"
export const RESET_STATE = "RESET_STATE_SETTING"
