export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"
export const ON_CHANGE = "SET_VALUE"
export const ACTION_LOADING = "ACTION_LOADING"
export const RESET_STATE = "RESET_STATE"
